#!/usr/bin/env bash

echo "Initiating build scipt..."
start=`date +%s`

CLIENT_PATH="./client"
SERVER_NODE_MODULES="./node_modules"
CLIENT_NODE_MODULES="$CLIENT_PATH/node_modules"

echo "SERVER NODE MODULES: $SERVER_NODE_MODULES"
echo "CLIENT NODE MODULES: $CLIENT_NODE_MODULES"

# Checks if pm2 is already installed
echo "Checking to see if PM2 is installed globally..."
(npm list -g pm2 && echo "PM2 is installed! Moving on...") || (echo "Installing PM2..." && npm install -g pm2@latest && pm2 update)

# Checks if react-scripts is already installed
echo "Checking to see if react-scripts is installed globally..."
(npm list -g react-scripts && echo "react-scripts is installed! Moving on...") || (echo "Installing react-scripts..." && npm install -g react-scripts@latest)

# Builds client
echo "Building client..."
npm run build --prefix client

end=`date +%s`
runtime=$((end-start))
echo "DONE: Build script completed in $runtime seconds."
