export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_LOADED = 'PROJECTS_LOADED';
export const PROJECTS_LOADED_ERROR = 'PROJECTS_LOADED_ERROR';
export const SET_PROJECTS = 'SET_PROJECTS';
